---
version: '3.7'

services:
  proxy:
    image: nginx:1.17
    volumes:
      - ./files/nginx/config:/etc/nginx/conf.d:ro
      - ./files/nginx/www:/usr/share/nginx/html:ro
    ports:
      - 0.0.0.0:80:80/tcp
...
